# Generated by Django 3.1.4 on 2020-12-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yop', models.IntegerField()),
                ('sp', models.IntegerField()),
                ('dist', models.IntegerField()),
                ('owners', models.IntegerField()),
                ('fuel', models.CharField(max_length=20)),
                ('owner_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
            ],
        ),
    ]
